//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.CMS.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ls_cmsEntities : DbContext
    {
        public ls_cmsEntities()
            : base("name=ls_cmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ls_log> ls_log { get; set; }
        public virtual DbSet<ls_nav> ls_nav { get; set; }
        public virtual DbSet<ls_role> ls_role { get; set; }
        public virtual DbSet<ls_role_nav> ls_role_nav { get; set; }
        public virtual DbSet<ls_user> ls_user { get; set; }
        public virtual DbSet<ls_user_role> ls_user_role { get; set; }
        public virtual DbSet<ls_visit_log> ls_visit_log { get; set; }
        public virtual DbSet<tour_area> tour_area { get; set; }
    }
}
