//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.CMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ls_user
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string user_mobile { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string user_salt { get; set; }
        public string user_avatar { get; set; }
        public Nullable<System.DateTime> user_birth { get; set; }
        public string nick_name { get; set; }
        public string real_name { get; set; }
        public System.DateTime create_time { get; set; }
        public string create_ip { get; set; }
        public int user_status { get; set; }
        public Nullable<int> user_gender { get; set; }
    }
}
