//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.CMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ls_visit_log
    {
        public System.Guid id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public string visit_ip { get; set; }
        public Nullable<System.DateTime> visit_time { get; set; }
        public string visit_url { get; set; }
        public string visit_area { get; set; }
        public string visit_os { get; set; }
        public string visit_browser { get; set; }
    }
}
