//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.CMS.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_area
    {
        public int id { get; set; }
        public string area_name { get; set; }
        public int area_type { get; set; }
        public string area_code { get; set; }
        public string parent_code { get; set; }
        public string area_longitude { get; set; }
        public string area_latitude { get; set; }
        public Nullable<int> key_times { get; set; }
        public string area_en { get; set; }
        public string area_alias { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_user { get; set; }
    }
}
